// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Anime struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Plot        string `json:"plot"`
}

type PaginationInput struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}
