// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anime.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Anime struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Plot                 string   `protobuf:"bytes,4,opt,name=plot,proto3" json:"plot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime) Reset()         { *m = Anime{} }
func (m *Anime) String() string { return proto.CompactTextString(m) }
func (*Anime) ProtoMessage()    {}
func (*Anime) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cdf86e3cafc4bf7, []int{0}
}

func (m *Anime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime.Unmarshal(m, b)
}
func (m *Anime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime.Marshal(b, m, deterministic)
}
func (m *Anime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime.Merge(m, src)
}
func (m *Anime) XXX_Size() int {
	return xxx_messageInfo_Anime.Size(m)
}
func (m *Anime) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime.DiscardUnknown(m)
}

var xxx_messageInfo_Anime proto.InternalMessageInfo

func (m *Anime) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Anime) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Anime) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Anime) GetPlot() string {
	if m != nil {
		return m.Plot
	}
	return ""
}

type GetAnimesRequest struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimesRequest) Reset()         { *m = GetAnimesRequest{} }
func (m *GetAnimesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnimesRequest) ProtoMessage()    {}
func (*GetAnimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cdf86e3cafc4bf7, []int{1}
}

func (m *GetAnimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimesRequest.Unmarshal(m, b)
}
func (m *GetAnimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimesRequest.Marshal(b, m, deterministic)
}
func (m *GetAnimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimesRequest.Merge(m, src)
}
func (m *GetAnimesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnimesRequest.Size(m)
}
func (m *GetAnimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimesRequest proto.InternalMessageInfo

func (m *GetAnimesRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAnimesRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetAnimesResponse struct {
	Animes               []*Anime `protobuf:"bytes,1,rep,name=animes,proto3" json:"animes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimesResponse) Reset()         { *m = GetAnimesResponse{} }
func (m *GetAnimesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnimesResponse) ProtoMessage()    {}
func (*GetAnimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cdf86e3cafc4bf7, []int{2}
}

func (m *GetAnimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimesResponse.Unmarshal(m, b)
}
func (m *GetAnimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimesResponse.Marshal(b, m, deterministic)
}
func (m *GetAnimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimesResponse.Merge(m, src)
}
func (m *GetAnimesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnimesResponse.Size(m)
}
func (m *GetAnimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimesResponse proto.InternalMessageInfo

func (m *GetAnimesResponse) GetAnimes() []*Anime {
	if m != nil {
		return m.Animes
	}
	return nil
}

type GetAnimeRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimeRequest) Reset()         { *m = GetAnimeRequest{} }
func (m *GetAnimeRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnimeRequest) ProtoMessage()    {}
func (*GetAnimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cdf86e3cafc4bf7, []int{3}
}

func (m *GetAnimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimeRequest.Unmarshal(m, b)
}
func (m *GetAnimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimeRequest.Marshal(b, m, deterministic)
}
func (m *GetAnimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimeRequest.Merge(m, src)
}
func (m *GetAnimeRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnimeRequest.Size(m)
}
func (m *GetAnimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimeRequest proto.InternalMessageInfo

func (m *GetAnimeRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAnimeResponse struct {
	Anime                *Anime   `protobuf:"bytes,1,opt,name=anime,proto3" json:"anime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimeResponse) Reset()         { *m = GetAnimeResponse{} }
func (m *GetAnimeResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnimeResponse) ProtoMessage()    {}
func (*GetAnimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cdf86e3cafc4bf7, []int{4}
}

func (m *GetAnimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimeResponse.Unmarshal(m, b)
}
func (m *GetAnimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimeResponse.Marshal(b, m, deterministic)
}
func (m *GetAnimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimeResponse.Merge(m, src)
}
func (m *GetAnimeResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnimeResponse.Size(m)
}
func (m *GetAnimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimeResponse proto.InternalMessageInfo

func (m *GetAnimeResponse) GetAnime() *Anime {
	if m != nil {
		return m.Anime
	}
	return nil
}

func init() {
	proto.RegisterType((*Anime)(nil), "pb.Anime")
	proto.RegisterType((*GetAnimesRequest)(nil), "pb.GetAnimesRequest")
	proto.RegisterType((*GetAnimesResponse)(nil), "pb.GetAnimesResponse")
	proto.RegisterType((*GetAnimeRequest)(nil), "pb.GetAnimeRequest")
	proto.RegisterType((*GetAnimeResponse)(nil), "pb.GetAnimeResponse")
}

func init() { proto.RegisterFile("anime.proto", fileDescriptor_5cdf86e3cafc4bf7) }

var fileDescriptor_5cdf86e3cafc4bf7 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x85, 0x52, 0x22, 0x83, 0xf1, 0xcf, 0x88, 0x86, 0x78, 0x91, 0xee, 0x89, 0x13, 0x87,
	0x36, 0xd1, 0xc4, 0x93, 0x9e, 0xbc, 0xe3, 0x13, 0x08, 0x4c, 0x93, 0x4d, 0x28, 0xbb, 0xb2, 0xab,
	0x2f, 0xe0, 0x8b, 0x1b, 0x06, 0xb6, 0x52, 0x6e, 0x3b, 0xbf, 0xf9, 0xe6, 0xfb, 0x66, 0xb2, 0x10,
	0x7f, 0x76, 0xf2, 0x40, 0x85, 0xee, 0x95, 0x55, 0xe8, 0xeb, 0x4a, 0xd4, 0xb0, 0x7e, 0x1b, 0x10,
	0x5e, 0x82, 0x2f, 0x9b, 0xd4, 0xcb, 0xbc, 0x3c, 0x28, 0x7d, 0xd9, 0x60, 0x02, 0x6b, 0x2b, 0x6d,
	0x4b, 0xa9, 0x9f, 0x79, 0x79, 0x54, 0x8e, 0x05, 0x66, 0x10, 0x37, 0x64, 0xea, 0x5e, 0x6a, 0x2b,
	0x55, 0x97, 0xae, 0xb8, 0x37, 0x47, 0x88, 0x10, 0xe8, 0x56, 0xd9, 0x34, 0xe0, 0x16, 0xbf, 0xc5,
	0x2b, 0x5c, 0xbf, 0x93, 0xe5, 0x1c, 0x53, 0xd2, 0xd7, 0x37, 0x19, 0x3b, 0xf8, 0xb7, 0xf2, 0x20,
	0xed, 0x14, 0x39, 0x16, 0x78, 0x0f, 0xa1, 0xda, 0xef, 0x0d, 0x59, 0x8e, 0x0d, 0xca, 0xa9, 0x12,
	0x4f, 0x70, 0x33, 0x73, 0x30, 0x5a, 0x75, 0x86, 0x70, 0x03, 0x21, 0x9f, 0x63, 0x52, 0x2f, 0x5b,
	0xe5, 0xf1, 0x36, 0x2a, 0x74, 0x55, 0xb0, 0xa6, 0x9c, 0x1a, 0x62, 0x03, 0x57, 0x6e, 0xce, 0x05,
	0x2f, 0x0e, 0x15, 0xbb, 0xff, 0xe5, 0x8e, 0xce, 0x8f, 0xb0, 0x66, 0x03, 0x96, 0x9d, 0x18, 0x8f,
	0x7c, 0xfb, 0xeb, 0xc1, 0x05, 0x83, 0x0f, 0xea, 0x7f, 0x64, 0x4d, 0xf8, 0x02, 0xd1, 0x71, 0x41,
	0x4c, 0x06, 0xfd, 0xf2, 0xe2, 0x87, 0xbb, 0x05, 0x1d, 0xb3, 0xc4, 0x19, 0x3e, 0xc3, 0xb9, 0xc3,
	0x78, 0x3b, 0x17, 0xb9, 0xc9, 0xe4, 0x14, 0xba, 0xc1, 0x2a, 0xe4, 0x7f, 0xdc, 0xfd, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xad, 0x56, 0x16, 0xbc, 0xd6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnimeServiceClient is the client API for AnimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnimeServiceClient interface {
	GetAnimes(ctx context.Context, in *GetAnimesRequest, opts ...grpc.CallOption) (*GetAnimesResponse, error)
	GetAnime(ctx context.Context, in *GetAnimeRequest, opts ...grpc.CallOption) (*GetAnimeResponse, error)
}

type animeServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnimeServiceClient(cc *grpc.ClientConn) AnimeServiceClient {
	return &animeServiceClient{cc}
}

func (c *animeServiceClient) GetAnimes(ctx context.Context, in *GetAnimesRequest, opts ...grpc.CallOption) (*GetAnimesResponse, error) {
	out := new(GetAnimesResponse)
	err := c.cc.Invoke(ctx, "/pb.AnimeService/GetAnimes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animeServiceClient) GetAnime(ctx context.Context, in *GetAnimeRequest, opts ...grpc.CallOption) (*GetAnimeResponse, error) {
	out := new(GetAnimeResponse)
	err := c.cc.Invoke(ctx, "/pb.AnimeService/GetAnime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimeServiceServer is the server API for AnimeService service.
type AnimeServiceServer interface {
	GetAnimes(context.Context, *GetAnimesRequest) (*GetAnimesResponse, error)
	GetAnime(context.Context, *GetAnimeRequest) (*GetAnimeResponse, error)
}

// UnimplementedAnimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAnimeServiceServer struct {
}

func (*UnimplementedAnimeServiceServer) GetAnimes(ctx context.Context, req *GetAnimesRequest) (*GetAnimesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimes not implemented")
}
func (*UnimplementedAnimeServiceServer) GetAnime(ctx context.Context, req *GetAnimeRequest) (*GetAnimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnime not implemented")
}

func RegisterAnimeServiceServer(s *grpc.Server, srv AnimeServiceServer) {
	s.RegisterService(&_AnimeService_serviceDesc, srv)
}

func _AnimeService_GetAnimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).GetAnimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnimeService/GetAnimes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).GetAnimes(ctx, req.(*GetAnimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimeService_GetAnime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).GetAnime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnimeService/GetAnime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).GetAnime(ctx, req.(*GetAnimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AnimeService",
	HandlerType: (*AnimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimes",
			Handler:    _AnimeService_GetAnimes_Handler,
		},
		{
			MethodName: "GetAnime",
			Handler:    _AnimeService_GetAnime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anime.proto",
}
